### ISSUE TITLE
Move into Homebrew organisation

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/rubocop-cask#59]
I think we should aim to move this into the Homebrew organisation and, ideally, move all the code into Homebrew/brew (like has been done with all Homebrew's cops). This would stop PRs like e.g. https://github.com/Homebrew/brew/pull/3876 being blocked on a new gem release.

**Comment by vitorgalvao** [comment]
Agreed.

**Comment by reitermarkus** [comment]
Yep.

**Comment by MikeMcQuaid** [comment]
This happened, thanks @reitermarkus!
