### ISSUE TITLE
Cop: check for comment when using :target with a named artifact

### ISSUE THREAD

**Issue by jawshooah** [Homebrew/rubocop-cask#6]
When an artifact like `app` uses `:target`, we expect to see a comment above it like this:

``` rb
# Renamed for clarity: app name is inconsistent with its branding.
```

or this:

``` rb
# Renamed for consistency: app name is different in the Finder and in a shell.
# Original discussion: https://github.com/caskroom/homebrew-cask/pull/7435
```

**Comment by MikeMcQuaid** [comment]
This repository has been deprecated and moved to Homebrew/brew in https://github.com/Homebrew/brew/pull/5190. Consider reopening this issue there if it's still needed.
