### ISSUE TITLE
Force array square brackets on separate line

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/rubocop-cask#64]
Copy of https://github.com/Homebrew/homebrew-cask/issues/50531 in the correct repo.

---

### Description of feature/enhancement

`brew cask style {cask_name}` should report and fix ruby array style.

### Justification

Maintainers do require square brackets to be on separate line, but rubocop doesn't report nor fix this.

### Example use case

https://github.com/Homebrew/homebrew-cask/commit/302910a652ec7a1fa1dc161434e0a52448c45a3d

**Comment by MikeMcQuaid** [comment]
This repository has been deprecated and moved to Homebrew/brew in https://github.com/Homebrew/brew/pull/5190. Consider reopening this issue there if it's still needed.
